[tool.poetry]
name = "pytket-qir"
version = "0.1.0"
description = ""
authors = ["Roland Guichard <roland.guichard@cambridgequantum.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pytket = "^1.3.0rc1"
pyqir = "^0.4.2a1"
requests = "^2.28.0"
websockets = "^10.3"
nest-asyncio = "^1.5.5"
PyJWT = "1.7.1"
keyring = "^23.6.0"
"keyrings.alt" = "^4.1.0"

[tool.poetry.scripts]
compile-bc-test-files = "tests.qir_test_files.compile_bc_test_files:compile_to_bc"

[tool.black]
exclude = '''

(
  /(
     notebooks
  )/

)
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
